apiVersion: v1
kind: Pod
metadata:
  name: nginx-worker1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  nodeName: worker1
---
apiVersion: v1
kind: Pod
metadata:
  name: bash-worker1
spec:
  containers:
  - name: ubuntu
    image: yoavklein3/net-tools:latest
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
  nodeName: worker1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-worker2
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  nodeName: worker2
---
apiVersion: v1
kind: Pod
metadata:
  name: bash-worker2
spec:
  containers:
  - name: ubuntu
    image: yoavklein3/net-tools:0.3
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
  nodeName: worker2
