apiVersion: v1
kind: Pod
metadata:
  name: echo-worker1
  labels:
    app: echo
spec:
  containers:
  - name: echo
    image: yoavklein3/echo:0.1
    ports:
    - containerPort: 5000
  nodeName: worker1
---
apiVersion: v1
kind: Pod
metadata:
  name: bash-worker1
spec:
  containers:
  - name: ubuntu
    image: yoavklein3/net-tools:latest
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
  nodeName: worker1
---
apiVersion: v1
kind: Pod
metadata:
  name: echo-worker2
  labels:
    app: echo
spec:
  containers:
  - name: echo
    image: echo
    ports:
    - containerPort: 5000
  nodeName: worker2
---
apiVersion: v1
kind: Pod
metadata:
  name: bash-worker2
spec:
  containers:
  - name: ubuntu
    image: yoavklein3/net-tools:0.3
    command:
      - "bin/bash"
      - "-c"
      - "sleep 10000"
  nodeName: worker2
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  type: ClusterIP
  selector:
    app: echo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
